In [5]:
import pandas as pd

In [8]:
cus_df = pd.read_csv('customers.csv')
cus_df.head()

,customer_id,email,full_name,country,created_at,updated_at,marketing_opt_in
0,CUST0001,user1@example.com,User 1,DE,2023-02-13 05:40:50,10/01/2023 17:07,0
1,CUST0002,user2@example.com,User 2,United Arab Emirates,2023-04-06 02:33:27,28/03/2023 16:28,N
2,CUST0003,user3@example.com,User 3,DE,2023-02-09 19:19:27,20/09/2023 19:17,0
3,CUST0004,user4@example.com,User 4,USA,2023-02-03 18:19:43,18/08/2023 07:47,false
4,CUST0005,user5@example.com,User 5,AE,2023-01-12 13:43:48,06/02/2023 09:18,N

In [17]:
list(cus_df.columns)

['customer_id',
 'email',
 'full_name',
 'country',
 'created_at',
 'updated_at',
 'marketing_opt_in']

In [10]:
rates_df = pd.read_csv('fx_rates.csv')
rates_df.head()

         date base_currency quote_currency    rate    source
0  2023-01-01           USD            USD  2.2557       ecb
1  2023-01-01           USD            EUR  1.8211  internal
2  2023-01-01           USD            AED  3.3474  internal
3  2023-01-02           USD            USD  1.2188       ecb
4  2023-01-02           USD            EUR  2.7290  internal

In [19]:
list(rates_df.columns)

['date', 'base_currency', 'quote_currency', 'rate', 'source']

In [11]:
clicks_df = pd.read_csv('marketing_clicks.csv')
clicks_df.head()

,click_id,customer_id,anonymous_id,channel,clicked_at,campaign,utm_source,utm_medium
0,CLK000001,CUST0418,NaN,tiktok,2023-07-10T07:12:01,Campaign_5,tiktok,email
1,CLK000002,CUST0061,NaN,email,2023-10-17T16:00:58,Campaign_1,tiktok,cpm
2,CLK000003,CUST0296,NaN,meta_ads,2023-05-02T06:46:22,Campaign_1,facebook,organic
3,CLK000004,CUST0139,NaN,tiktok,2023-11-23T09:05:19,Campaign_3,newsletter,organic
4,CLK000005,CUST0290,NaN,email,2023-12-27T08:25:52,Campaign_9,google,cpm

In [20]:
list(clicks_df.columns)

['click_id',
 'customer_id',
 'anonymous_id',
 'channel',
 'clicked_at',
 'campaign',
 'utm_source',
 'utm_medium']

In [12]:
items_df = pd.read_csv('order_items.csv')
items_df.head()

,order_item_id,order_id,product_sku,product_name,quantity,unit_price,line_discount
0,ITEM000001,ORD00254,SKU154,Product 41,3,175.21,17.03
1,ITEM000002,ORD00992,SKU698,Product 32,2,146.82,15.69
2,ITEM000003,ORD00810,SKU779,Product 40,1,37.65,7.76
3,ITEM000004,ORD00904,SKU760,Product 49,3,102.22,9.29
4,ITEM000005,ORD00330,SKU829,Product 24,-1,144.55,9.90

In [21]:
list(items_df.columns)

['order_item_id',
 'order_id',
 'product_sku',
 'product_name',
 'quantity',
 'unit_price',
 'line_discount']

In [13]:
orders_df = pd.read_csv('orders.csv')
orders_df.head()

,order_id,customer_id,order_created_at,order_updated_at,status,currency,order_total,shipping_amount,discount_amount
0,ORD00001,CUST0180,2023-01-03T08:54:36,03-12-2023 10:49:20,shipped,NaN,44.10,14.82,48.59
1,ORD00002,CUST0047,2023-10-17T18:15:56,07-26-2023 00:27:25,shipped,NaN,215.72,6.82,18.50
2,ORD00003,CUST0370,2023-05-06T23:28:03,10-29-2023 16:37:57,COMPLETE,USD,442.84,3.11,37.72
3,ORD00004,CUST0026,2023-09-19T17:50:37,02-01-2023 16:23:41,cancelled,NaN,334.35,9.71,22.10
4,ORD00005,CUST0140,2023-03-25T17:14:54,10-21-2023 04:34:48,COMPLETE,USD,179.13,2.22,33.91

In [22]:
list(orders_df.columns)

['order_id',
 'customer_id',
 'order_created_at',
 'order_updated_at',
 'status',
 'currency',
 'order_total',
 'shipping_amount',
 'discount_amount']

In [14]:
payments_df = pd.read_csv('payments.csv')
payments_df.head()

,payment_id,order_id,attempt_number,payment_provider,payment_method,status,amount,currency,created_at,processed_at,failure_reason
0,PAY000001,ORD00622,2,adyen,bank_transfer,partially_refunded,235.40,AED,2023/01/03 16:27,2023-05-26T08:18:44,NaN
1,PAY000002,ORD00051,1,STRIPE,bank_transfer,refunded,425.31,AED,2023/02/04 10:45,2023-07-30T12:22:25,NaN
2,PAY000003,ORD00877,1,stripe,bank_transfer,captured,90.33,AED,2023/05/20 18:19,2023-06-17T23:04:03,NaN
3,PAY000004,ORD00223,1,STRIPE,bank_transfer,partially_refunded,352.32,USD,2023/11/02 07:17,2023-09-23T02:24:29,insufficient_funds
4,PAY000005,ORD00580,2,adyen,apple_pay,authorized,101.16,AED,2023/12/24 21:33,2023-02-21T19:06:41,NaN

In [23]:
list(payments_df.columns)

['payment_id',
 'order_id',
 'attempt_number',
 'payment_provider',
 'payment_method',
 'status',
 'amount',
 'currency',
 'created_at',
 'processed_at',
 'failure_reason']

In [15]:
refunds_df = pd.read_csv('refunds.csv')
refunds_df.head()

,refund_id,payment_id,order_id,refund_amount,currency,reason,refunded_at
0,REF00001,PAY001081,ORD00125,25.53,AED,customer_request,23-01-2023 23:40
1,REF00002,PAY000191,ORD00524,88.07,EUR,customer_request,22-02-2023 18:40
2,REF00003,PAY000507,ORD00086,163.74,EUR,duplicate,28-05-2023 04:07
3,REF00004,PAY000762,ORD00100,104.47,USD,customer_request,30-06-2023 02:09
4,REF00005,PAY000753,ORD00609,20.73,EUR,customer_request,09-01-2023 09:05

In [24]:
list(refunds_df.columns)

['refund_id',
 'payment_id',
 'order_id',
 'refund_amount',
 'currency',
 'reason',
 'refunded_at']